-- Generated by the database client.
CREATE TABLE task_entity(
    id varchar(255) NOT NULL,
    
    is_archived boolean,
    title varchar(255),

    m_id1 varchar(255),
    v_code1 varchar(255),
    
    m_id2 varchar(255),
    v_code2 varchar(255),
    PRIMARY KEY(id)
);