-- Generated by the database client.
CREATE TABLE task_entity(
    id varchar(36) NOT NULL UNIQUE,
    uid VARCHAR(36) not NULL,

    created TIMESTAMP without time zone,
    is_archived boolean, title varchar(127),

    m1_id varchar(36),
    v_code1 varchar(36),
    
    m2_id varchar(36),
    v_code2 varchar(36),
    
    PRIMARY KEY(id)
);